### ISSUE TITLE
How to change OS icon?

### ISSUE THREAD

**Issue by viperperidot** [sandesh236/sleek--themes#2]
How do I change the icon that displays beside each OS in the Grub menu?

I have Kubuntu installed but it displays the Ubuntu logo beside the menu item instead of the Kubuntu logo.

**Comment by sandesh236** [comment]
just add icons in the icons folder. use proper name of the os on icon.

**Comment by viperperidot** [comment]
It looks like the Kubuntu icon is already in the icon folder, but how does the theme determine which icon to use? That seems to be what I need to edit.

**Comment by HardcodeCoder** [comment]
> It looks like the Kubuntu icon is already in the icon folder, but how does the theme determine which icon to use? That seems to be what I need to edit.

Just overwrite the `kubuntu.png` file with whatever icon you want (make sure it has the same dimensions).

**Comment by thiagolucio** [comment]
Same here. 
I'm using Fedora 34. 
I tried to put manually the icon in the configuration file of the theme, in theme.txt but not solve. 

I tried to put this...

```
  icon = "fedora.png"
  icon_width = 32
  icon_height = 32
```

But not working. 

I'm not found any lines used to reference any S.O icons inside "theme.txt" and I think the first question made by @viperperidot  it's about this question. What command We can put to force show the icon?

**Comment by sandesh236** [comment]
It's not about the command, you have to just put the icons in the icons folder, have a proper name for it. Grub bootloader lists the operating systems and searches icons for them on the icons folder.  I think the fedora icon is already present in the icons folder. try renaming it to fedora34.png, If it works, let me know. Thank you...

**Comment by thiagolucio** [comment]
> It's not about the command, you have to just put the icons in the icons folder, have a proper name for it. Grub bootloader lists the operating systems and searches icons for them on the icons folder. I think the fedora icon is already present in the icons folder. try renaming it to fedora34.png, If it works, let me know. Thank you...

I did the renaming procedure to "fedora34.png" but the problem remains. I did a system search (since I don't know where the path comes from to determine which icon should be used, that is. Where the theme collects system information to decide which icon to show) and found all fedora logo images in the system. So I also tried by deduction to apply this name to see if it would work (fedora-logo.png) but it didn't work either.

How is this icon chosen in the theme? Where does it capture the information to define which icon to show? Probably the problem is taking place because of this.
